# Generated by Django 5.0.3 on 2024-04-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=50)),
                ('bed', models.CharField(max_length=10)),
                ('priceperb', models.CharField(max_length=10)),
                ('deposite', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
            ],
        ),
    ]
