# Generated by Django 5.0.3 on 2024-04-13 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cout',
        ),
    ]
