# Generated by Django 5.0.3 on 2024-04-20 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_cout'),
    ]

    operations = [
        migrations.CreateModel(
            name='cout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=50)),
                ('bed', models.CharField(max_length=10)),
                ('priceperb', models.CharField(max_length=10)),
                ('deposite', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.CharField(max_length=10)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.signup')),
            ],
        ),
    ]
