# Generated by Django 5.0.3 on 2024-04-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_cout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bed',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
