# Generated by Django 5.0.3 on 2024-04-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='firstname',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
