# Generated by Django 5.0.3 on 2024-04-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_order_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='loadcheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=10)),
                ('rbed', models.CharField(max_length=10)),
                ('bprice', models.CharField(max_length=10)),
                ('btotal', models.CharField(max_length=10)),
            ],
        ),
    ]
