# Generated by Django 5.0.3 on 2024-04-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_loadcheckout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loadcheckout',
        ),
    ]
