# Generated by Django 5.0.3 on 2024-04-23 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_loadcheckout'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('blog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.blog')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.order')),
            ],
        ),
    ]
