# Generated by Django 5.0.3 on 2024-04-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_blogorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='blog_data',
            field=models.TextField(blank=True),
        ),
    ]
