# Generated by Django 5.0.3 on 2024-04-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_order_blog_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
    ]
