# Generated by Django 5.0.3 on 2024-04-24 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_signup_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='blog_data',
        ),
    ]
